### ISSUE TITLE
It's 4 bits here, and some other things are not right

### ISSUE THREAD

**Issue by yiheng-wu** [ruggiero/clustep#1]
https://github.com/ruggiero/clustep/blob/0e41de2c4249a7da02b4f4cc6f5f2a0c456f902c/analysis/snapread.py#L13
It should be replaced by read_dummy(snapshot,1)
The py cannot run, I think there are some similar problems.
Would you please check it?
Thanks.

**Comment by ruggiero** [comment]
Hi @yihenginthehell, sorry about the delayed response. I haven't used this particular script in ages, because I have replaced it with [pygadgetreader](https://bitbucket.org/rthompson/pygadgetreader), which is much better. I suggest you give it a try.
